services:
  game2gather-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: game2gather-db
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Game_2_Gather
      MSSQL_DB: game2gather
      MSSQL_USER: game2gather
      MSSQL_PASSWORD: Game_2_Gather
    ports:
      - "1433:1433"
