spring:
  sql:
    init:
      data-locations: classpath:testdata/gamesData.sql
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=game2gather;encrypt=true;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: SA
    password: Game_2_Gather
  liquibase:
    change-log: "db/db.changelog-master.xml"

